[[language]]
name = "latex"
language-servers = [ "texlab", "ltex"]



[language-server.texlab]
command = "/opt/homebrew/bin/texlab"

[language-server.texlab.config.texlab.build]
onSave = true
# forwardSearchAfter = true

[language-server.texlab.config.texlab.forwardSearch]
# executable = "evince"
# args = [ "--synctex-forward", "%l:1:%f", "%p" ]

[language-server.texlab.config.texlab.chktex]
#onEdit = true

[language-server.ltex]
command = "/opt/homebrew/bin/ltex-ls"
